"""add_dlq_messages_table

Revision ID: 1f6cfdb87ee4
Revises: 455b5310a90b
Create Date: 2026-02-28 14:15:08.838280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f6cfdb87ee4'
down_revision: Union[str, Sequence[str], None] = '455b5310a90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dlq_messages',
    sa.Column('queue_name', sa.String(length=255), nullable=False, comment='DLQ queue name the message was consumed from'),
    sa.Column('message_body', sa.Text(), nullable=False, comment='Original message payload (UTF-8)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Stringified exception from the final failure'),
    sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Original AMQP headers (x-retry-attempt, x-original-queue, etc.)'),
    sa.Column('attempt_count', sa.Integer(), nullable=False, comment='Number of retry attempts before dead-lettering'),
    sa.Column('status', sa.Enum('PENDING', 'RETRIED', 'DISCARDED', name='dlq_message_status', native_enum=False), nullable=False, comment='Lifecycle status: pending → retried | discarded'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlq_messages_queue_name'), 'dlq_messages', ['queue_name'], unique=False)
    op.create_index('ix_dlq_messages_queue_status', 'dlq_messages', ['queue_name', 'status'], unique=False)
    op.create_index(op.f('ix_dlq_messages_status'), 'dlq_messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dlq_messages_status'), table_name='dlq_messages')
    op.drop_index('ix_dlq_messages_queue_status', table_name='dlq_messages')
    op.drop_index(op.f('ix_dlq_messages_queue_name'), table_name='dlq_messages')
    op.drop_table('dlq_messages')
    # ### end Alembic commands ###
