"""Add fingerprint_hash and access_status to usage_logs

Revision ID: 3198391c30ab
Revises: 3f69fe220c23
Create Date: 2026-02-11 23:59:05.396988

"""

from typing import Sequence, Union
import hashlib
import hmac
import json

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3198391c30ab"
down_revision: Union[str, Sequence[str], None] = "3f69fe220c23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_legacy_fingerprint(endpoint: str, method: str) -> str:
    """Create a fingerprint for legacy records without payload_hash."""
    data = {
        "endpoint": endpoint.lower().strip() if endpoint else "/legacy/unknown",
        "method": method.upper().strip() if method else "UNKNOWN",
        "payload_hash": "legacy_no_payload_hash",
        "usage_estimate": None,
    }
    canonical = json.dumps(data, sort_keys=True, separators=(",", ":"))
    secret = "request_fingerprint_v1"
    hash_obj = hmac.new(
        secret.encode("utf-8"),
        canonical.encode("utf-8"),
        hashlib.sha256,
    )
    return hash_obj.hexdigest()


def upgrade() -> None:
    """Upgrade schema.

    Add fingerprint_hash and access_status columns:
    - fingerprint_hash: Hash for idempotency (endpoint+method+payload_hash+usage_estimate)
    - access_status: The access decision ('granted' or 'denied')

    Also changes the unique constraint from request_id only to (request_id, fingerprint_hash).
    """
    # Step 1: Add columns as nullable first
    op.add_column(
        "usage_logs",
        sa.Column(
            "fingerprint_hash",
            sa.String(length=64),
            nullable=True,
            comment="Hash of endpoint+method+payload_hash+usage_estimate for idempotency",
        ),
    )
    op.add_column(
        "usage_logs",
        sa.Column(
            "access_status",
            sa.String(length=10),
            nullable=True,
            comment="Access decision: 'granted' or 'denied'",
        ),
    )

    # Step 2: Backfill existing rows
    conn = op.get_bind()
    usage_logs = sa.table(
        "usage_logs",
        sa.column("id"),
        sa.column("endpoint"),
        sa.column("method"),
        sa.column("fingerprint_hash"),
        sa.column("access_status"),
    )

    # Get existing rows without fingerprint_hash
    result = conn.execute(
        sa.select(usage_logs.c.id, usage_logs.c.endpoint, usage_logs.c.method).where(
            usage_logs.c.fingerprint_hash.is_(None)
        )
    )
    for row in result:
        fingerprint = _create_legacy_fingerprint(row.endpoint, row.method)
        conn.execute(
            usage_logs.update()
            .where(usage_logs.c.id == row.id)
            .values(
                fingerprint_hash=fingerprint,
                access_status="denied",  # Legacy records default to denied
            )
        )

    # Step 3: Add NOT NULL constraints
    op.alter_column("usage_logs", "fingerprint_hash", nullable=False)
    op.alter_column("usage_logs", "access_status", nullable=False)

    # Step 4: Update indexes
    # Drop old unique index on request_id
    op.drop_index(op.f("ix_usage_logs_request_id"), table_name="usage_logs")
    # Create non-unique index on request_id
    op.create_index(
        op.f("ix_usage_logs_request_id"), "usage_logs", ["request_id"], unique=False
    )
    # Create index on fingerprint_hash
    op.create_index(
        op.f("ix_usage_logs_fingerprint_hash"),
        "usage_logs",
        ["fingerprint_hash"],
        unique=False,
    )
    # Create unique composite index on (request_id, fingerprint_hash)
    op.create_index(
        "ix_usage_logs_request_fingerprint",
        "usage_logs",
        ["request_id", "fingerprint_hash"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_logs_request_fingerprint", table_name="usage_logs")
    op.drop_index(op.f("ix_usage_logs_fingerprint_hash"), table_name="usage_logs")
    op.drop_index(op.f("ix_usage_logs_request_id"), table_name="usage_logs")
    op.create_index(
        op.f("ix_usage_logs_request_id"), "usage_logs", ["request_id"], unique=True
    )
    op.drop_column("usage_logs", "access_status")
    op.drop_column("usage_logs", "fingerprint_hash")
    # ### end Alembic commands ###
