"""update_usage_logs_idempotency_index_add_workspace_id

Revision ID: 43aabe22da72
Revises: 3198391c30ab
Create Date: 2026-02-12 00:19:40.412576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43aabe22da72'
down_revision: Union[str, Sequence[str], None] = '3198391c30ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_request_fingerprint'), table_name='usage_logs')
    op.create_index('ix_usage_logs_request_fingerprint_workspace', 'usage_logs', ['request_id', 'fingerprint_hash', 'workspace_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_logs_request_fingerprint_workspace', table_name='usage_logs')
    op.create_index(op.f('ix_usage_logs_request_fingerprint'), 'usage_logs', ['request_id', 'fingerprint_hash'], unique=True)
    # ### end Alembic commands ###
