"""add_career_usage_logs_and_quota_columns

Revision ID: 9407500c9344
Revises: b1a2c3d4e5f6
Create Date: 2026-02-26 20:02:41.717691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "9407500c9344"
down_revision: Union[str, Sequence[str], None] = "b1a2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "career_usage_logs",
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="User who made this request"
        ),
        sa.Column(
            "subscription_id",
            sa.UUID(),
            nullable=False,
            comment="Denormalized for efficient subscription-level queries",
        ),
        sa.Column(
            "request_id",
            sa.String(),
            nullable=False,
            comment="Globally unique request ID for idempotency",
        ),
        sa.Column(
            "fingerprint_hash",
            sa.String(length=64),
            nullable=False,
            comment="Hash of endpoint+method+payload_hash+usage_estimate for idempotency",
        ),
        sa.Column(
            "access_status",
            sa.String(length=10),
            nullable=False,
            comment="Access decision: 'granted' or 'denied'",
        ),
        sa.Column(
            "feature_key",
            sa.Enum(
                "API_CAREER_PATH",
                "API_EXTRACT_KEYWORDS",
                "API_FEEDBACK_ANALYZER",
                "API_GENERATE_FEEDBACK",
                "API_JOB_MATCH",
                "API_EXTRACT_CUES_RESUME",
                "API_EXTRACT_CUES_FEEDBACK",
                "API_EXTRACT_CUES_INTERVIEW",
                "API_EXTRACT_CUES_ASSESSMENT",
                "API_REFRAME_FEEDBACK",
                "CAREER_CAREER_PATH",
                "CAREER_EXTRACT_KEYWORDS",
                "CAREER_FEEDBACK_ANALYZER",
                "CAREER_GENERATE_FEEDBACK",
                "CAREER_JOB_MATCH",
                "CAREER_EXTRACT_CUES_RESUME",
                "CAREER_EXTRACT_CUES_FEEDBACK",
                "CAREER_EXTRACT_CUES_INTERVIEW",
                "CAREER_EXTRACT_CUES_ASSESSMENT",
                "CAREER_REFRAME_FEEDBACK",
                name="feature_key",
                native_enum=False,
            ),
            nullable=False,
            comment="Feature Key (e.g., 'career.career_path')",
        ),
        sa.Column(
            "endpoint",
            sa.String(),
            nullable=False,
            comment="The API endpoint path being called",
        ),
        sa.Column(
            "method",
            sa.String(),
            nullable=False,
            comment="HTTP method (GET, POST, etc.)",
        ),
        sa.Column(
            "client_ip",
            sa.String(),
            nullable=True,
            comment="Optional client IP address",
        ),
        sa.Column(
            "client_user_agent",
            sa.String(),
            nullable=True,
            comment="Optional client user agent string",
        ),
        sa.Column(
            "usage_estimate",
            sa.JSON(),
            nullable=True,
            comment="Usage estimation data (input_chars, max_output_tokens, model)",
        ),
        sa.Column(
            "credits_reserved",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="The billable cost in credits",
        ),
        sa.Column(
            "credits_charged",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
            comment="Actual credits charged on commit (null for pending/failed)",
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "SUCCESS",
                "FAILED",
                "EXPIRED",
                name="usagelogstatus",
                create_type=False,
            ),
            nullable=False,
            comment="Status of this usage log entry",
        ),
        sa.Column(
            "committed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the status changed from PENDING",
        ),
        sa.Column(
            "model_used",
            sa.String(length=100),
            nullable=True,
            comment="Model identifier used (e.g., 'gpt-4o')",
        ),
        sa.Column(
            "input_tokens",
            sa.Integer(),
            nullable=True,
            comment="Actual input tokens used",
        ),
        sa.Column(
            "output_tokens",
            sa.Integer(),
            nullable=True,
            comment="Actual output tokens generated",
        ),
        sa.Column(
            "latency_ms",
            sa.Integer(),
            nullable=True,
            comment="Request latency in milliseconds",
        ),
        sa.Column(
            "failure_type",
            sa.Enum(
                "INTERNAL_ERROR",
                "TIMEOUT",
                "RATE_LIMITED",
                "INVALID_RESPONSE",
                "UPSTREAM_ERROR",
                "CLIENT_ERROR",
                "VALIDATION_ERROR",
                name="failure_type",
                native_enum=False,
            ),
            nullable=True,
            comment="Category of failure when status=FAILED",
        ),
        sa.Column(
            "failure_reason",
            sa.String(length=1000),
            nullable=True,
            comment="Human-readable failure description",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Immutable usage log. Only status/committed_at can be updated.",
    )
    op.create_index(
        "ix_career_usage_logs_endpoint", "career_usage_logs", ["endpoint"], unique=False
    )
    op.create_index(
        op.f("ix_career_usage_logs_failure_type"),
        "career_usage_logs",
        ["failure_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_usage_logs_feature_key"),
        "career_usage_logs",
        ["feature_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_usage_logs_fingerprint_hash"),
        "career_usage_logs",
        ["fingerprint_hash"],
        unique=False,
    )
    op.create_index(
        "ix_career_usage_logs_request_fingerprint_user",
        "career_usage_logs",
        ["request_id", "fingerprint_hash", "user_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_career_usage_logs_request_id"),
        "career_usage_logs",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        "ix_career_usage_logs_status", "career_usage_logs", ["status"], unique=False
    )
    op.create_index(
        "ix_career_usage_logs_subscription_created",
        "career_usage_logs",
        ["subscription_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_usage_logs_subscription_id"),
        "career_usage_logs",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "ix_career_usage_logs_user_created",
        "career_usage_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_career_usage_logs_user_id"),
        "career_usage_logs",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "career_subscription_contexts",
        sa.Column(
            "credits_used",
            sa.Numeric(precision=12, scale=2),
            server_default="0.00",
            nullable=False,
            comment="Running total of credits consumed in current billing period",
        ),
    )
    op.add_column(
        "career_subscription_contexts",
        sa.Column(
            "billing_period_start",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Start of current billing period (for reset detection)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("career_subscription_contexts", "billing_period_start")
    op.drop_column("career_subscription_contexts", "credits_used")
    op.drop_index(op.f("ix_career_usage_logs_user_id"), table_name="career_usage_logs")
    op.drop_index("ix_career_usage_logs_user_created", table_name="career_usage_logs")
    op.drop_index(
        op.f("ix_career_usage_logs_subscription_id"), table_name="career_usage_logs"
    )
    op.drop_index(
        "ix_career_usage_logs_subscription_created", table_name="career_usage_logs"
    )
    op.drop_index("ix_career_usage_logs_status", table_name="career_usage_logs")
    op.drop_index(
        op.f("ix_career_usage_logs_request_id"), table_name="career_usage_logs"
    )
    op.drop_index(
        "ix_career_usage_logs_request_fingerprint_user", table_name="career_usage_logs"
    )
    op.drop_index(
        op.f("ix_career_usage_logs_fingerprint_hash"), table_name="career_usage_logs"
    )
    op.drop_index(
        op.f("ix_career_usage_logs_feature_key"), table_name="career_usage_logs"
    )
    op.drop_index(
        op.f("ix_career_usage_logs_failure_type"), table_name="career_usage_logs"
    )
    op.drop_index("ix_career_usage_logs_endpoint", table_name="career_usage_logs")
    op.drop_table("career_usage_logs")
    # ### end Alembic commands ###
