"""auto

Revision ID: 967d49c9390e
Revises: f22dc778ae5b
Create Date: 2026-02-22 17:50:16.929403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '967d49c9390e'
down_revision: Union[str, Sequence[str], None] = 'f22dc778ae5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_cost_configs',
    sa.Column('feature_key', sa.Enum('API_CAREER_PATH', 'API_EXTRACT_KEYWORDS', 'API_FEEDBACK_ANALYZER', 'API_GENERATE_FEEDBACK', 'API_JOB_MATCH', 'API_EXTRACT_CUES_RESUME', 'API_EXTRACT_CUES_FEEDBACK', 'API_EXTRACT_CUES_INTERVIEW', 'API_EXTRACT_CUES_ASSESSMENT', 'API_REFRAME_FEEDBACK', 'CAREER_CAREER_PATH', 'CAREER_EXTRACT_KEYWORDS', 'CAREER_FEEDBACK_ANALYZER', 'CAREER_GENERATE_FEEDBACK', 'CAREER_JOB_MATCH', 'CAREER_EXTRACT_CUES_RESUME', 'CAREER_EXTRACT_CUES_FEEDBACK', 'CAREER_EXTRACT_CUES_INTERVIEW', 'CAREER_EXTRACT_CUES_ASSESSMENT', 'CAREER_REFRAME_FEEDBACK', name='feature_key', native_enum=False), nullable=False, comment="Feature Key (e.g., 'api.analyze')"),
    sa.Column('product_type', sa.Enum('API', 'CAREER', name='product_type', native_enum=False), nullable=False, comment='Product this plan belongs to (API or CAREER)'),
    sa.Column('internal_cost_credits', sa.Numeric(precision=12, scale=2), nullable=False, comment='Internal credit cost for this feature'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_cost_configs_feature_key'), 'feature_cost_configs', ['feature_key'], unique=True)
    op.create_index('ix_feature_cost_configs_feature_lookup', 'feature_cost_configs', ['feature_key'], unique=False)
    op.create_index(op.f('ix_feature_cost_configs_product_type'), 'feature_cost_configs', ['product_type'], unique=False)
    op.drop_index(op.f('ix_endpoint_cost_configs_endpoint'), table_name='endpoint_cost_configs')
    op.drop_index(op.f('ix_endpoint_cost_configs_endpoint_lookup'), table_name='endpoint_cost_configs')
    op.drop_table('endpoint_cost_configs')
    op.add_column('plan_pricing_rules', sa.Column('rate_limit_per_day', sa.Integer(), nullable=True, comment='Maximum API requests allowed per day'))
    op.alter_column('plan_pricing_rules', 'rate_limit_per_minute',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Maximum API requests allowed per minute',
               existing_server_default=sa.text('20'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_pricing_rules', 'rate_limit_per_minute',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Maximum API requests allowed per minute',
               existing_server_default=sa.text('20'))
    op.drop_column('plan_pricing_rules', 'rate_limit_per_day')
    op.create_table('endpoint_cost_configs',
    sa.Column('endpoint', sa.VARCHAR(length=512), autoincrement=False, nullable=False, comment="API endpoint path (e.g., '/api/v1/analyze')"),
    sa.Column('internal_cost_credits', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, comment='Internal credit cost for this endpoint'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('endpoint_cost_configs_pkey'))
    )
    op.create_index(op.f('ix_endpoint_cost_configs_endpoint_lookup'), 'endpoint_cost_configs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_endpoint_cost_configs_endpoint'), 'endpoint_cost_configs', ['endpoint'], unique=True)
    op.drop_index(op.f('ix_feature_cost_configs_product_type'), table_name='feature_cost_configs')
    op.drop_index('ix_feature_cost_configs_feature_lookup', table_name='feature_cost_configs')
    op.drop_index(op.f('ix_feature_cost_configs_feature_key'), table_name='feature_cost_configs')
    op.drop_table('feature_cost_configs')
    # ### end Alembic commands ###
