"""Add product_type and subscription context tables

Revision ID: 9972f699afcf
Revises: 25b42df44e3f
Create Date: 2026-02-02 11:29:48.550475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9972f699afcf'
down_revision: Union[str, Sequence[str], None] = '25b42df44e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('display_price', sa.String(length=64), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('FREE', 'PAID', name='plan_type', native_enum=False), nullable=False),
    sa.Column('product_type', sa.Enum('API', 'CAREER', name='product_type', native_enum=False), nullable=False, comment='Product this plan belongs to (API or CAREER)'),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=True, comment='Maximum seats allowed (None = unlimited)'),
    sa.Column('min_seats', sa.Integer(), server_default='1', nullable=False, comment='Minimum seats required'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_seats IS NULL OR max_seats >= min_seats', name='ck_plans_max_seats_valid'),
    sa.CheckConstraint('min_seats >= 1', name='ck_plans_min_seats_positive'),
    sa.CheckConstraint('price >= 0', name='ck_plans_price_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_plans_name')
    )
    op.create_index(op.f('ix_plans_is_active'), 'plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.create_index(op.f('ix_plans_product_type'), 'plans', ['product_type'], unique=False)
    op.create_index(op.f('ix_plans_stripe_price_id'), 'plans', ['stripe_price_id'], unique=False)
    op.create_index(op.f('ix_plans_type'), 'plans', ['type'], unique=False)
    op.create_table('stripe_event_logs',
    sa.Column('event_id', sa.String(length=128), nullable=False, comment='Stripe event ID for deduplication'),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_event_logs_event_id'), 'stripe_event_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_stripe_event_logs_event_type'), 'stripe_event_logs', ['event_type'], unique=False)
    op.create_table('subscriptions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('product_type', sa.Enum('API', 'CAREER', name='product_type', native_enum=False), nullable=False, comment='Product this subscription belongs to (API or CAREER)'),
    sa.Column('stripe_subscription_id', sa.String(length=128), nullable=True, comment='Stripe Subscription ID (null for free plans)'),
    sa.Column('stripe_customer_id', sa.String(length=128), nullable=True, comment='Stripe Customer ID'),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'INCOMPLETE', 'INCOMPLETE_EXPIRED', 'TRIALING', 'UNPAID', 'PAUSED', name='subscription_status', native_enum=False), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False, comment='Number of seats purchased'),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Current billing amount per period'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('seat_count >= 1', name='ck_subscriptions_seat_count_positive'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_product_type'), 'subscriptions', ['product_type'], unique=False)
    op.create_index('ix_subscriptions_product_type_status', 'subscriptions', ['product_type', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_table('workspaces',
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False, comment="URL-friendly identifier (e.g., 'ws-john-doe-1')"),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FROZEN', 'SUSPENDED', name='workspace_status', native_enum=False), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False, comment='Personal workspaces are auto-created and cannot be deleted'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_workspaces_slug')
    )
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_index('ix_workspaces_owner_personal', 'workspaces', ['owner_id', 'is_personal'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_index(op.f('ix_workspaces_status'), 'workspaces', ['status'], unique=False)
    op.create_table('api_subscription_contexts',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', name='uq_api_subscription_context_subscription'),
    sa.UniqueConstraint('workspace_id', name='uq_api_subscription_context_workspace')
    )
    op.create_index(op.f('ix_api_subscription_contexts_subscription_id'), 'api_subscription_contexts', ['subscription_id'], unique=True)
    op.create_index(op.f('ix_api_subscription_contexts_workspace_id'), 'api_subscription_contexts', ['workspace_id'], unique=True)
    op.create_table('career_subscription_contexts',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', name='uq_career_subscription_context_subscription'),
    sa.UniqueConstraint('user_id', name='uq_career_subscription_context_user')
    )
    op.create_index(op.f('ix_career_subscription_contexts_subscription_id'), 'career_subscription_contexts', ['subscription_id'], unique=True)
    op.create_index(op.f('ix_career_subscription_contexts_user_id'), 'career_subscription_contexts', ['user_id'], unique=True)
    op.create_table('workspace_invitations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('inviter_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='member_role', native_enum=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='HMAC-SHA256 hash of invitation token'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitation_status', native_enum=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_invitations_email'), 'workspace_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_workspace_invitations_inviter_id'), 'workspace_invitations', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_workspace_invitations_status'), 'workspace_invitations', ['status'], unique=False)
    op.create_index('ix_workspace_invitations_token_hash', 'workspace_invitations', ['token_hash'], unique=False)
    op.create_index('ix_workspace_invitations_workspace_email_pending', 'workspace_invitations', ['workspace_id', 'email'], unique=False, postgresql_where="status = 'pending'")
    op.create_index(op.f('ix_workspace_invitations_workspace_id'), 'workspace_invitations', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='member_role', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', name='member_status', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_members_workspace_user')
    )
    op.create_index(op.f('ix_workspace_members_status'), 'workspace_members', ['status'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index('ix_workspace_members_user_status', 'workspace_members', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_index('ix_workspace_members_workspace_status', 'workspace_members', ['workspace_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_members_workspace_status', table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index('ix_workspace_members_user_status', table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_status'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspace_invitations_workspace_id'), table_name='workspace_invitations')
    op.drop_index('ix_workspace_invitations_workspace_email_pending', table_name='workspace_invitations', postgresql_where="status = 'pending'")
    op.drop_index('ix_workspace_invitations_token_hash', table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_status'), table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_inviter_id'), table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_email'), table_name='workspace_invitations')
    op.drop_table('workspace_invitations')
    op.drop_index(op.f('ix_career_subscription_contexts_user_id'), table_name='career_subscription_contexts')
    op.drop_index(op.f('ix_career_subscription_contexts_subscription_id'), table_name='career_subscription_contexts')
    op.drop_table('career_subscription_contexts')
    op.drop_index(op.f('ix_api_subscription_contexts_workspace_id'), table_name='api_subscription_contexts')
    op.drop_index(op.f('ix_api_subscription_contexts_subscription_id'), table_name='api_subscription_contexts')
    op.drop_table('api_subscription_contexts')
    op.drop_index(op.f('ix_workspaces_status'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index('ix_workspaces_owner_personal', table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_product_type_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_product_type'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_stripe_event_logs_event_type'), table_name='stripe_event_logs')
    op.drop_index(op.f('ix_stripe_event_logs_event_id'), table_name='stripe_event_logs')
    op.drop_table('stripe_event_logs')
    op.drop_index(op.f('ix_plans_type'), table_name='plans')
    op.drop_index(op.f('ix_plans_stripe_price_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_product_type'), table_name='plans')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_is_active'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
