"""add_credits_allocation_and_rate_limit_to_plan_pricing_rules

Revision ID: a6601ad683a9
Revises: 43aabe22da72
Create Date: 2026-02-12 01:09:20.185229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6601ad683a9"
down_revision: Union[str, Sequence[str], None] = "43aabe22da72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan_pricing_rules",
        sa.Column(
            "credits_allocation",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            server_default="5000.0",
            comment="Credits allocated to users on this plan",
        ),
    )
    op.add_column(
        "plan_pricing_rules",
        sa.Column(
            "rate_limit_per_minute",
            sa.Integer(),
            nullable=False,
            server_default="20",
            comment="Maximum API requests allowed per minute",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan_pricing_rules", "rate_limit_per_minute")
    op.drop_column("plan_pricing_rules", "credits_allocation")
    # ### end Alembic commands ###
