"""Add metrics and failure tracking fields to usage_logs

Revision ID: abd07d38eb10
Revises: a6601ad683a9
Create Date: 2026-02-12 14:02:37.966647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd07d38eb10'
down_revision: Union[str, Sequence[str], None] = 'a6601ad683a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_logs', sa.Column('model_used', sa.String(length=100), nullable=True, comment="Model identifier used (e.g., 'gpt-4o')"))
    op.add_column('usage_logs', sa.Column('input_tokens', sa.Integer(), nullable=True, comment='Actual input tokens used'))
    op.add_column('usage_logs', sa.Column('output_tokens', sa.Integer(), nullable=True, comment='Actual output tokens generated'))
    op.add_column('usage_logs', sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Request latency in milliseconds'))
    op.add_column('usage_logs', sa.Column('failure_type', sa.Enum('INTERNAL_ERROR', 'TIMEOUT', 'RATE_LIMITED', 'INVALID_RESPONSE', 'UPSTREAM_ERROR', 'CLIENT_ERROR', 'VALIDATION_ERROR', name='failure_type', native_enum=False), nullable=True, comment='Category of failure when status=FAILED'))
    op.add_column('usage_logs', sa.Column('failure_reason', sa.String(length=1000), nullable=True, comment='Human-readable failure description'))
    op.create_index(op.f('ix_usage_logs_failure_type'), 'usage_logs', ['failure_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_failure_type'), table_name='usage_logs')
    op.drop_column('usage_logs', 'failure_reason')
    op.drop_column('usage_logs', 'failure_type')
    op.drop_column('usage_logs', 'latency_ms')
    op.drop_column('usage_logs', 'output_tokens')
    op.drop_column('usage_logs', 'input_tokens')
    op.drop_column('usage_logs', 'model_used')
    # ### end Alembic commands ###
