"""Add is_test_key column to api_keys table

Revision ID: cbda072cd66c
Revises: e282af0d077b
Create Date: 2026-02-13 17:47:07.136558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbda072cd66c"
down_revision: Union[str, Sequence[str], None] = "e282af0d077b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column(
            "is_test_key",
            sa.Boolean(),
            nullable=False,
            server_default="false",
            comment="Whether this is a test key (no credits charged)",
        ),
    )
    op.create_index(
        op.f("ix_api_keys_is_test_key"), "api_keys", ["is_test_key"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_api_keys_is_test_key"), table_name="api_keys")
    op.drop_column("api_keys", "is_test_key")
    # ### end Alembic commands ###
