"""Add endpoint_cost_configs and plan_pricing_rules tables

Revision ID: d4187500b13c
Revises: 1c3bb63c6b57
Create Date: 2026-02-11 20:17:09.066321

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4187500b13c"
down_revision: Union[str, Sequence[str], None] = "1c3bb63c6b57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoint_cost_configs",
        sa.Column(
            "endpoint",
            sa.String(length=512),
            nullable=False,
            comment="API endpoint path (e.g., '/api/v1/analyze')",
        ),
        sa.Column(
            "internal_cost_credits",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Internal credit cost for this endpoint",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_endpoint_cost_configs_endpoint"),
        "endpoint_cost_configs",
        ["endpoint"],
        unique=True,
    )
    op.create_index(
        "ix_endpoint_cost_configs_endpoint_lookup",
        "endpoint_cost_configs",
        ["endpoint"],
        unique=False,
    )
    op.create_table(
        "plan_pricing_rules",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column(
            "multiplier",
            sa.Numeric(precision=8, scale=2),
            nullable=False,
            comment="Pricing multiplier (1.0 = standard rate)",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", name="uq_plan_pricing_rules_plan_id"),
    )
    op.create_index(
        op.f("ix_plan_pricing_rules_plan_id"),
        "plan_pricing_rules",
        ["plan_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_plan_pricing_rules_plan_id"), table_name="plan_pricing_rules"
    )
    op.drop_table("plan_pricing_rules")
    op.drop_index(
        "ix_endpoint_cost_configs_endpoint_lookup", table_name="endpoint_cost_configs"
    )
    op.drop_index(
        op.f("ix_endpoint_cost_configs_endpoint"), table_name="endpoint_cost_configs"
    )
    op.drop_table("endpoint_cost_configs")
    # ### end Alembic commands ###
