"""remove_billing_period_start_from_contexts

Revision ID: d77c282ab61b
Revises: 9407500c9344
Create Date: 2026-02-26 20:13:47.633515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd77c282ab61b'
down_revision: Union[str, Sequence[str], None] = '9407500c9344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_subscription_contexts', 'billing_period_start')
    op.drop_column('career_subscription_contexts', 'billing_period_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_subscription_contexts', sa.Column('billing_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Start of current billing period (for reset detection)'))
    op.add_column('api_subscription_contexts', sa.Column('billing_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Start of current billing period (for reset detection)'))
    # ### end Alembic commands ###
