"""Add credits tracking to subscription context and usage logs

Revision ID: dfaab36ab65d
Revises: abd07d38eb10
Create Date: 2026-02-12 21:10:44.069753

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfaab36ab65d"
down_revision: Union[str, Sequence[str], None] = "abd07d38eb10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_subscription_contexts",
        sa.Column(
            "credits_used",
            sa.Numeric(precision=12, scale=2),
            server_default="0.00",
            nullable=False,
            comment="Running total of credits consumed in current billing period",
        ),
    )
    op.add_column(
        "api_subscription_contexts",
        sa.Column(
            "billing_period_start",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Start of current billing period (for reset detection)",
        ),
    )
    op.add_column(
        "usage_logs",
        sa.Column(
            "credits_charged",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
            comment="Actual credits charged on commit (null for pending/failed)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_logs", "credits_charged")
    op.drop_column("api_subscription_contexts", "billing_period_start")
    op.drop_column("api_subscription_contexts", "credits_used")
    # ### end Alembic commands ###
