"""auto

Revision ID: e282af0d077b
Revises: dfaab36ab65d
Create Date: 2026-02-12 21:57:39.376490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e282af0d077b'
down_revision: Union[str, Sequence[str], None] = 'dfaab36ab65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint_cost_configs', 'internal_cost_credits',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               existing_comment='Internal credit cost for this endpoint',
               existing_nullable=False)
    op.alter_column('plan_pricing_rules', 'multiplier',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=8, scale=2),
               existing_comment='Pricing multiplier (1.0 = standard rate)',
               existing_nullable=False)
    op.alter_column('plan_pricing_rules', 'credits_allocation',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               existing_comment='Credits allocated to users on this plan',
               existing_nullable=False,
               existing_server_default=sa.text('5000.0'))
    op.alter_column('usage_logs', 'credits_reserved',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=12, scale=2),
               existing_comment='The billable cost in credits',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_logs', 'credits_reserved',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_comment='The billable cost in credits',
               existing_nullable=False)
    op.alter_column('plan_pricing_rules', 'credits_allocation',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_comment='Credits allocated to users on this plan',
               existing_nullable=False,
               existing_server_default=sa.text('5000.0'))
    op.alter_column('plan_pricing_rules', 'multiplier',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_comment='Pricing multiplier (1.0 = standard rate)',
               existing_nullable=False)
    op.alter_column('endpoint_cost_configs', 'internal_cost_credits',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_comment='Internal credit cost for this endpoint',
               existing_nullable=False)
    # ### end Alembic commands ###
