"""Add plan name enums and CHECK constraint

Revision ID: e2eb115ac408
Revises: 9972f699afcf
Create Date: 2026-02-02 13:37:58.072622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2eb115ac408"
down_revision: Union[str, Sequence[str], None] = "9972f699afcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plans",
        "name",
        existing_type=sa.VARCHAR(length=128),
        comment="Plan name - must match product_type",
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_plans_name"), "plans", type_="unique")
    op.drop_index(op.f("ix_plans_name"), table_name="plans")
    op.create_index(op.f("ix_plans_name"), "plans", ["name"], unique=False)
    op.create_unique_constraint(
        "uq_plans_name_product_type", "plans", ["name", "product_type"]
    )

    # Add CHECK constraint for plan name validation
    op.create_check_constraint(
        "ck_plans_name_matches_product_type",
        "plans",
        """
        (product_type = 'API' AND name IN ('Free', 'Basic', 'Professional'))
        OR
        (product_type = 'CAREER' AND name IN ('Free', 'Plus Plan', 'Pro Plan'))
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop CHECK constraint first
    op.drop_constraint("ck_plans_name_matches_product_type", "plans", type_="check")

    op.drop_constraint("uq_plans_name_product_type", "plans", type_="unique")
    op.drop_index(op.f("ix_plans_name"), table_name="plans")
    op.create_index(op.f("ix_plans_name"), "plans", ["name"], unique=True)
    op.create_unique_constraint(
        op.f("uq_plans_name"), "plans", ["name"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "plans",
        "name",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="Plan name - must match product_type",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
