"""add_api_keys_and_usage_logs_tables

Revision ID: e7f189aed198
Revises: f3a9b8c7d6e5
Create Date: 2026-02-08 00:14:07.056736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f189aed198'
down_revision: Union[str, Sequence[str], None] = 'f3a9b8c7d6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='User-defined label for the API key'),
    sa.Column('key_hash', sa.String(length=64), nullable=False, comment='HMAC-SHA256 hash of the API key for secure lookup'),
    sa.Column('key_prefix', sa.String(length=20), nullable=False, comment='Display prefix: cbx_live_ + first 5 chars of token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When the key expires (null = never expires)'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When the key was revoked (null = not revoked)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the key is active and can be used'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last time the key was used for a request'),
    sa.Column('scopes', sa.JSON(), nullable=True, comment='Optional permission scopes for future use'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index('ix_api_keys_workspace_active', 'api_keys', ['workspace_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False, comment='Denormalized for efficient workspace-level quota queries'),
    sa.Column('cost', sa.JSON(), nullable=True, comment='Usage cost/credits consumed (structure TBD by quota system)'),
    sa.Column('reverted', sa.Boolean(), nullable=False, comment='Whether this usage has been reverted/refunded'),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=True, comment='When the usage was reverted'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Immutable usage log. Only reverted/reverted_at can be updated.'
    )
    op.create_index('ix_usage_logs_api_key_created', 'usage_logs', ['api_key_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_api_key_id'), 'usage_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_reverted'), 'usage_logs', ['reverted'], unique=False)
    op.create_index('ix_usage_logs_workspace_created', 'usage_logs', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_workspace_id'), 'usage_logs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_workspace_id'), table_name='usage_logs')
    op.drop_index('ix_usage_logs_workspace_created', table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_reverted'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_api_key_id'), table_name='usage_logs')
    op.drop_index('ix_usage_logs_api_key_created', table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_api_keys_workspace_id'), table_name='api_keys')
    op.drop_index('ix_api_keys_workspace_active', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
