"""Add rank field to plans

Revision ID: f22dc778ae5b
Revises: cbda072cd66c
Create Date: 2026-02-15 00:21:03.191904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f22dc778ae5b"
down_revision: Union[str, Sequence[str], None] = "cbda072cd66c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plans",
        sa.Column(
            "rank",
            sa.Integer(),
            nullable=True,
            comment="Plan rank for ordering (0 = lowest tier, higher = more expensive)",
        ),
    )

    # Populate ranks for API and CAREER plans
    # Lowest price gets rank 0, next gets rank 1, etc.
    op.execute(
        """
        WITH ranked_plans AS (
            SELECT
                id,
                product_type,
                ROW_NUMBER() OVER (
                    PARTITION BY product_type
                    ORDER BY price ASC
                ) - 1 AS computed_rank
            FROM plans
            WHERE product_type IN ('API', 'CAREER')
        )
        UPDATE plans
        SET rank = ranked_plans.computed_rank
        FROM ranked_plans
        WHERE plans.id = ranked_plans.id;
        """
    )
    op.alter_column("plans", "rank", nullable=False)
    op.create_unique_constraint(
        "uq_plans_rank_product_type", "plans", ["rank", "product_type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_plans_rank_product_type", "plans", type_="unique")
    op.drop_column("plans", "rank")
    # ### end Alembic commands ###
