"""add_seat_pricing_to_plans

Revision ID: f4dba42a4be4
Revises: 717db4fc10c9
Create Date: 2026-02-10 14:23:09.952302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4dba42a4be4"
down_revision: Union[str, Sequence[str], None] = "717db4fc10c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plans",
        sa.Column(
            "seat_price",
            sa.Numeric(precision=10, scale=2),
            server_default="0.00",
            nullable=False,
            comment="Per-seat monthly price",
        ),
    )
    op.add_column(
        "plans",
        sa.Column(
            "seat_display_price",
            sa.String(length=64),
            nullable=True,
            comment="Human-readable seat price (e.g., '$5/seat/month')",
        ),
    )
    op.add_column(
        "plans",
        sa.Column(
            "seat_stripe_price_id",
            sa.String(length=128),
            nullable=True,
            comment="Stripe Price ID for per-seat billing",
        ),
    )
    op.alter_column(
        "plans",
        "stripe_price_id",
        existing_type=sa.VARCHAR(length=128),
        comment="Stripe Price ID for base subscription",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_plans_seat_stripe_price_id"),
        "plans",
        ["seat_stripe_price_id"],
        unique=False,
    )

    # Add new check constraints
    op.create_check_constraint(
        "ck_plans_seat_price_non_negative", "plans", "seat_price >= 0"
    )
    op.create_check_constraint(
        "ck_plans_paid_has_stripe_id",
        "plans",
        "type = 'FREE' OR (type = 'PAID' AND (stripe_price_id IS NOT NULL OR seat_stripe_price_id IS NOT NULL))",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraints first
    op.drop_constraint("ck_plans_paid_has_stripe_id", "plans", type_="check")
    op.drop_constraint("ck_plans_seat_price_non_negative", "plans", type_="check")

    op.drop_index(op.f("ix_plans_seat_stripe_price_id"), table_name="plans")
    op.alter_column(
        "plans",
        "stripe_price_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="Stripe Price ID for base subscription",
        existing_nullable=True,
    )
    op.drop_column("plans", "seat_stripe_price_id")
    op.drop_column("plans", "seat_display_price")
    op.drop_column("plans", "seat_price")
    # ### end Alembic commands ###
